### ISSUE TITLE
set image on the whole screen

### ISSUE THREAD

**Issue by syrakozz** [davemorrissey/subsampling-scale-image-view#109] opened 2015-09-01 10:54 UTC
how i can make the image fullfill the whole screen,  i dont want the image to shrink to fit, 
and i check the sample code i didnt find anything usefull for my case, 
what do you suggest

**Comment by davemorrissey** [comment] 2015-09-01 11:00
Please read the wiki - setMinimumScaleType(SCALE_TYPE_CENTER_CROP). Duplicate of #108.

**Closed by davemorrissey** 2015-09-01 11:00 UTC
