### ISSUE TITLE
Create Multiple Pin

### ISSUE THREAD

**Issue by derah** [davemorrissey/subsampling-scale-image-view#236] opened 2016-07-30 15:25 UTC
I want to create multiple pin on an image .. 
how to create that ?
if only single pin, i have been do that..

**Comment by davemorrissey** [comment] 2016-07-30 20:02
Duplicate of #142

**Closed by davemorrissey** 2016-07-30 20:02 UTC

**Comment by calvingoc** [comment] 2017-07-27 18:56
There is probably a better way to do this but I changed the class to what I copied below. Now to add a pin you give it a point and a name and as long as each point has a unique name you can add as many as you want. You can remove any point by calling the removePin(String nameOfPinToRemove) function and can get an array of all the pins you currently have with the getPinNames() function.


package com.etcconnect.productlocationproposal;

/**
 * Created by cgehred on 7/26/2017.
 */

import android.content.Context;
import android.graphics.*;
import android.util.AttributeSet;
import com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView;

import java.lang.reflect.Array;
import java.util.ArrayList;


public class PinView extends SubsamplingScaleImageView {

    private ArrayList<PointF> sPin = new ArrayList<>();
    private ArrayList<String> pinNames = new ArrayList<>();
    private Bitmap pin;

    public PinView(Context context) {
        this(context, null);
    }

    public PinView(Context context, AttributeSet attr) {
        super(context, attr);
        initialise();
    }

    public boolean setPin(PointF sPin, String name) {
        if (pinNames.contains(name)){
            return false;
        } else {
            this.sPin.add(sPin);
            pinNames.add(name);
            initialise();
            invalidate();
            return true;
        }
    }

    public PointF getPin(String name) {

        return sPin.get(pinNames.indexOf(name));
    }

    public boolean removePin(String name){
        if (pinNames.contains(name)){
            sPin.remove(pinNames.indexOf(name));
            pinNames.remove(name);
            return true;
        } else {
            return false;
        }
    }

    public ArrayList<String> getPinNames(){
        return pinNames;
    }

    private void initialise() {
        float density = getResources().getDisplayMetrics().densityDpi;
        pin = BitmapFactory.decodeResource(this.getResources(), R.drawable.pin);
        float w = (density/420f) * pin.getWidth();
        float h = (density/420f) * pin.getHeight();
        pin = Bitmap.createScaledBitmap(pin, (int)w, (int)h, true);
    }

    @Override
    protected void onDraw(Canvas canvas) {
        super.onDraw(canvas);

        // Don't draw pin before image is ready so it doesn't move around during setup.
        if (!isReady()) {
            return;
        }

        Paint paint = new Paint();
        paint.setAntiAlias(true);
        for (PointF point : sPin){
            if (point != null && pin != null) {
                PointF vPin = sourceToViewCoord(point);
                float vX = vPin.x - (pin.getWidth()/2);
                float vY = vPin.y - pin.getHeight();
                canvas.drawBitmap(pin, vX, vY, paint);
            }
        }
    }

}

**Comment by mirza04** [comment] 2018-06-26 12:09
Hey, how can we just use the extension pin fragment(the image with the fixed pins)  on its own

**Comment by fukemy** [comment] 2019-01-25 04:42
hi @calvingoc , can u explain why need to use 420f in line of code: 
```
float w = (density/420f) * pin.getWidth();
float h = (density/420f) * pin.getHeight();
```

Sorry if it's a silly question, as my knowledge not all device have same density
