### ISSUE TITLE
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@3a1f4260

### ISSUE THREAD

**Issue by lomoya90** [davemorrissey/subsampling-scale-image-view#280] opened 2016-12-30 09:46 UTC
java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@3a1f4260
	at android.graphics.Canvas.throwIfCannotDraw(Canvas.java:1282)
	at android.view.GLES20Canvas.drawBitmap(GLES20Canvas.java:593)
	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onDraw(SubsamplingScaleImageView.java:1127)

**Comment by davemorrissey** [comment] 2016-12-30 10:29
Duplicate of #213. Please search closed issues before raising a new one.

**Closed by davemorrissey** 2016-12-30 10:29 UTC

**Comment by lomoya90** [comment] 2016-12-31 09:06
Thank you! I see it, but why?
