### ISSUE TITLE
SubsamplingScaleImageView.preDraw:  java.lang.NullPointerException: Attempt to read from field 'float android.graphics.PointF.x' on a null object reference

### ISSUE THREAD

**Issue by penmatsa** [davemorrissey/subsampling-scale-image-view#469] opened 2019-07-15 14:15 UTC
com.hycite.docucite.zoom.library.SubsamplingScaleImageView.preDraw SubsamplingScaleImageView.java:1294
com.hycite.docucite.zoom.library.SubsamplingScaleImageView.checkReady SubsamplingScaleImageView.java:1129
com.hycite.docucite.zoom.library.SubsamplingScaleImageView.onDraw SubsamplingScaleImageView.java:937
android.view.View.draw View.java:21869
android.view.View.updateDisplayListIfDirty View.java:20742
android.view.View.draw View.java:21595
android.view.ViewGroup.drawChild ViewGroup.java:4553
android.view.ViewGroup.dispatchDraw ViewGroup.java:4328
android.view.View.updateDisplayListIfDirty View.java:20728
android.view.View.draw View.java:21595
android.view.ViewGroup.drawChild ViewGroup.java:4553
android.view.ViewGroup.dispatchDraw ViewGroup.java:4328
android.view.View.updateDisplayListIfDirty View.java:20728
android.view.View.draw View.java:21595
android.view.ViewGroup.drawChild ViewGroup.java:4553
android.view.ViewGroup.dispatchDraw ViewGroup.java:4328
android.view.View.updateDisplayListIfDirty View.java:20728
android.view.View.draw View.java:21595
android.view.ViewGroup.drawChild ViewGroup.java:4553
android.view.ViewGroup.dispatchDraw ViewGroup.java:4328
android.view.View.draw View.java:21872
android.view.View.updateDisplayListIfDirty View.java:20742
android.view.View.draw View.java:21595
android.view.ViewGroup.drawChild ViewGroup.java:4553
android.view.ViewGroup.dispatchDraw ViewGroup.java:4328
android.view.View.draw View.java:21872
android.view.View.updateDisplayListIfDirty View.java:20742
android.view.View.draw View.java:21595
android.view.ViewGroup.drawChild ViewGroup.java:4553
android.support.design.widget.CoordinatorLayout.drawChild CoordinatorLayout.java:1254
android.view.ViewGroup.dispatchDraw ViewGroup.java:4328
android.view.View.draw View.java:21872
android.view.View.updateDisplayListIfDirty View.java:20742
android.view.View.draw View.java:21595
android.view.ViewGroup.drawChild ViewGroup.java:4553
android.view.ViewGroup.dispatchDraw ViewGroup.java:4328
android.view.View.draw View.java:21872
android.view.View.updateDisplayListIfDirty View.java:20742
android.view.View.draw View.java:21595
android.view.ViewGroup.drawChild ViewGroup.java:4553
android.view.ViewGroup.dispatchDraw ViewGroup.java:4328
android.view.View.updateDisplayListIfDirty View.java:20728
android.view.View.draw View.java:21595
android.view.ViewGroup.drawChild ViewGroup.java:4553
android.view.ViewGroup.dispatchDraw ViewGroup.java:4328
android.view.View.updateDisplayListIfDirty View.java:20728
android.view.View.draw View.java:21595
android.view.ViewGroup.drawChild ViewGroup.java:4553
android.view.ViewGroup.dispatchDraw ViewGroup.java:4328
android.view.View.updateDisplayListIfDirty View.java:20728
android.view.View.draw View.java:21595
android.view.ViewGroup.drawChild ViewGroup.java:4553
android.view.ViewGroup.dispatchDraw ViewGroup.java:4328
android.view.View.updateDisplayListIfDirty View.java:20728
android.view.View.draw View.java:21595
android.view.ViewGroup.drawChild ViewGroup.java:4553
android.view.ViewGroup.dispatchDraw ViewGroup.java:4328
android.view.View.draw View.java:21872
com.android.internal.policy.DecorView.draw DecorView.java:1082
android.view.View.updateDisplayListIfDirty View.java:20742
android.view.ThreadedRenderer.updateViewTreeDisplayList ThreadedRenderer.java:725
android.view.ThreadedRenderer.updateRootDisplayList ThreadedRenderer.java:731
android.view.ThreadedRenderer.draw ThreadedRenderer.java:840
android.view.ViewRootImpl.draw ViewRootImpl.java:3912
android.view.ViewRootImpl.performDraw ViewRootImpl.java:3686
android.view.ViewRootImpl.performTraversals ViewRootImpl.java:2994
android.view.ViewRootImpl.doTraversal ViewRootImpl.java:1853
android.view.ViewRootImpl$TraversalRunnable.run ViewRootImpl.java:8476
android.view.Choreographer$CallbackRecord.run Choreographer.java:949
android.view.Choreographer.doCallbacks Choreographer.java:761
android.view.Choreographer.doFrame Choreographer.java:696
android.view.Choreographer$FrameDisplayEventReceiver.run Choreographer.java:935
android.os.Handler.handleCallback Handler.java:873
android.os.Handler.dispatchMessage Handler.java:99
android.os.Looper.loop Looper.java:214
android.app.ActivityThread.main ActivityThread.java:7045
java.lang.reflect.Method.invoke Method.java
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run RuntimeInit.java:493
com.android.internal.os.ZygoteInit.main ZygoteInit.java:964

**Comment by davemorrissey** [comment] 2020-02-26 23:03
Closing because the issue template has been deleted and not enough information has been provided to reproduce this issue.

**Closed by davemorrissey** 2020-02-26 23:03 UTC
