### ISSUE TITLE
Unable to get image bitmap from SubsamplingScaleImageView

### ISSUE THREAD

**Issue by SSeanSS** [davemorrissey/subsampling-scale-image-view#287] opened 2017-01-20 08:23 UTC
`
Bitmap bitmap = iv.getDrawingCache();
if(bitmap==null) {
            Toast.makeText(context, context.getResources().getString(R.string.toastImageUnloaded), Toast.LENGTH_LONG).show();
            return;
        }
`

My image is loaded into SubsamplingScaleImageView but i got no way to retrieve the bitmap back from it.

**Comment by davemorrissey** [comment] 2017-01-20 09:17
Duplicate of #19, #57, #104, #196, #264, #276. Please check closed issues before raising a new one! Answers also available on StackOverflow.

**Closed by davemorrissey** 2017-01-20 09:17 UTC
