### ISSUE TITLE
Transition Resize Problem

### ISSUE THREAD

**Issue by ronysaguntara** [davemorrissey/subsampling-scale-image-view#417] opened 2018-04-16 01:24 UTC
Shared element transition does not work properly because the size of the image does not automatically follow the parent view size. and i tried to manually by changing the layoutParams it also can not resize automatically. I tried with the default imageView it runs fine. can you help me?

**Comment by davemorrissey** [comment] 2018-04-16 05:33
Duplicate of #313

**Closed by davemorrissey** 2018-04-16 05:33 UTC
