### ISSUE TITLE
Can't load bitmap

### ISSUE THREAD

**Issue by Coletz** [davemorrissey/subsampling-scale-image-view#217] opened 2016-06-03 09:05 UTC
I try to load a bitmap like this
```
SubsamplingScaleImageView imageView = (SubsamplingScaleImageView) findViewById(R.id.map);
BitmapFactory.Options opt = new BitmapFactory.Options();
opt.inMutable = true;
Bitmap bitmap = BitmapFactory.decodeResource(getResources(), R.drawable.map, opt);
if(imageView != null){
    imageView.setImage(ImageSource.bitmap(bitmap));
}
```
but I get an exception:
```
E/SubsamplingScaleImageView: Failed to load bitmap
java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String android.net.Uri.toString()' on a null object reference
at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1571)
at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1551)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:818)
```
I need to load bitmap and not resource because I need to add an overlay to the image, so between the decode and the setImage I have other methods that edit the bitmap

**Comment by davemorrissey** [comment] 2016-06-03 11:49
Are you using an old or modified version of the library? There's nothing on lines 1571 or 1551.

**Comment by Coletz** [comment] 2016-06-03 12:14
I'm using the 3.5.0, including it with gradle
`compile 'com.davemorrissey.labs:subsampling-scale-image-view:3.5.0'`
I've downloaded the lib to try to fix this problem and I've seen that the real problem is at 1576
by the way, I've seen that this problem won't persist using a different image. In fact I was using a ~2.3mb image, and then I've compressed it with tinypng website. Using the compressed image I have no crash loading it. If you want to investigate over this, I'll leave here the original and the compressed image
![map](https://cloud.githubusercontent.com/assets/6728530/15778200/e3e88396-2994-11e6-95ac-f6be4dc4ec72.jpg)
![map](https://cloud.githubusercontent.com/assets/6728530/15778237/29a98a7e-2995-11e6-9e13-f13ec46e29f6.jpg)

**Comment by davemorrissey** [comment] 2016-06-03 15:07
Could you include more of your code between decoding the bitmap and adding it to the view?

**Comment by Coletz** [comment] 2016-06-03 15:12
I haven't more code at the moment, my activity is 1:1 the code I've posted

**Comment by davemorrissey** [comment] 2016-06-18 20:32
I can't reproduce this problem, both images load normally for me.

**Comment by davemorrissey** [comment] 2016-06-28 10:21
Any updates on how I can reproduce this or can I close it?

**Comment by Coletz** [comment] 2016-06-28 10:31
I have no idea on how to reproduce it. Moreover I'm having this issue only with my Xiaomi Redmi Note 3. Moto G and Nexus 5 doesn't behave like this. I've changed the image and problem doesn't appear. It was a modded phone with chinese rom, so imho you can close it. Thanks for your time

**Closed** 2016-06-28 16:32 UTC

**Comment by mguilhermetavares** [comment] 2017-01-25 21:35
If you load Bitmap from Picasso you can see this error.

**Comment by pamartineza** [comment] 2017-04-17 11:02
I have users reporting this problem on Xiaomi Note 4 too, I think is issue is somehow related with this vendor

**Comment by kazajiru** [comment] 2017-10-08 11:57
I get this issue in 2 situations:
- if I predefine image in android:src and then setting image bitmap in onCreate
- if I use setImage from drawable and after a while setImage from bitmap. 
In my case: setting placeholder image and then getting image from Glide cache.

So I guess it a sort of concurrent exception
