### ISSUE TITLE
get Bitmap from ScaleImageView

### ISSUE THREAD

**Issue by tuhin10** [davemorrissey/subsampling-scale-image-view#104] opened 2015-08-22 17:44 UTC
How can i get bitmap from ScaleImageView?? We retrive a bitmap from an ImageView like this

Bitmap bm=((BitmapDrawable)mImageView.getDrawable()).getBitmap();

Is there any way get the bitmap ???

**Comment by davemorrissey** [comment] 2015-08-23 14:28
Duplicate of #19

**Closed by davemorrissey** 2015-08-23 14:28 UTC
