### ISSUE TITLE
Out of Memory when rotating

### ISSUE THREAD

**Issue by PetrDana** [davemorrissey/subsampling-scale-image-view#48] opened 2015-03-09 09:45 UTC
Hi, some users reports Out of Memory when they use rotate of viewed image. On my device (Samsung Galaxy Note II) is this problem too. I tested it on version 2.3.0 also but this problem is there still.
Rotate button has this simple functionality:

```java
int actualOrientation = mPicture.getOrientation();
mPicture.setOrientation(actualOrientation == 270 ? 0 : actualOrientation + 90);
```

I add logs to SubsamplingScaleImageView.BitmapTileTask.doInBackground() to synchronized block before decodeRegion and before createBitmap with tag SUBSAMPLING ROTATE (this is in exception log below).
The proble is that bitmap gets big dimensions from decodeRegion - dimensions are original of image source with sampleSize = 1.
Is there another procedure for change orientation for eliminate Out of Memory?

```
D/SUBSAMPLING ROTATE﹕ tile: Rect(0, 0 - 2448, 3264); sampleSize: 1
D/dalvikvm﹕ GC_FOR_ALLOC freed 5088K, 41% free 27412K/45956K, paused 25ms, total 26ms
I/dalvikvm-heap﹕ Grow heap (frag case) to 43.484MB for 15980560-byte allocation
D/dalvikvm﹕ GC_FOR_ALLOC freed 329K, 31% free 42689K/61564K, paused 17ms, total 17ms
D/SUBSAMPLING ROTATE﹕ bitmap dim: 3264 x 2448
D/dalvikvm﹕ GC_FOR_ALLOC freed 1K, 31% free 42689K/61564K, paused 15ms, total 15ms
I/dalvikvm-heap﹕ Forcing collection of SoftReferences for 15980560-byte allocation
D/dalvikvm﹕ GC_BEFORE_OOM freed 70K, 31% free 42618K/61564K, paused 27ms, total 27ms
E/dalvikvm-heap﹕ Out of memory on a 15980560-byte allocation.
I/dalvikvm﹕ "AsyncTask #2" prio=5 tid=12 RUNNABLE
I/dalvikvm﹕ | group="main" sCount=0 dsCount=0 obj=0x4368dde0 self=0x5b526ce0
I/dalvikvm﹕ | sysTid=31125 nice=10 sched=0/0 cgrp=apps/bg_non_interactive handle=1532129584
I/dalvikvm﹕ | state=R schedstat=( 562850949 168737745 1402 ) utm=46 stm=10 core=3
I/dalvikvm﹕ at android.graphics.Bitmap.nativeCreate(Native Method)
I/dalvikvm﹕ at android.graphics.Bitmap.createBitmap(Bitmap.java:726)
I/dalvikvm﹕ at android.graphics.Bitmap.createBitmap(Bitmap.java:703)
I/dalvikvm﹕ at android.graphics.Bitmap.createBitmap(Bitmap.java:636)
I/dalvikvm﹕ at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapTileTask.doInBackground(SubsamplingScaleImageView.java:1197)
I/dalvikvm﹕ at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapTileTask.doInBackground(SubsamplingScaleImageView.java:1167)
I/dalvikvm﹕ at android.os.AsyncTask$2.call(AsyncTask.java:287)
I/dalvikvm﹕ at java.util.concurrent.FutureTask.run(FutureTask.java:234)
I/dalvikvm﹕ at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
I/dalvikvm﹕ at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
I/dalvikvm﹕ at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
I/dalvikvm﹕ at java.lang.Thread.run(Thread.java:841)
I/dalvikvm﹕ [ 03-09 10:24:31.503 31026:31125 W/dalvikvm ]
    threadid=12: thread exiting with uncaught exception (group=0x4195b700)
E/AndroidRuntime﹕ FATAL EXCEPTION: AsyncTask #2
    java.lang.RuntimeException: An error occured while executing doInBackground()
            at android.os.AsyncTask$3.done(AsyncTask.java:299)
            at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
            at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
            at java.util.concurrent.FutureTask.run(FutureTask.java:239)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
     Caused by: java.lang.OutOfMemoryError
            at android.graphics.Bitmap.nativeCreate(Native Method)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:726)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:703)
            at android.graphics.Bitmap.createBitmap(Bitmap.java:636)
            at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapTileTask.doInBackground(SubsamplingScaleImageView.java:1197)
            at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapTileTask.doInBackground(SubsamplingScaleImageView.java:1167)
            at android.os.AsyncTask$2.call(AsyncTask.java:287)
            at java.util.concurrent.FutureTask.run(FutureTask.java:234)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
            at java.lang.Thread.run(Thread.java:841)
D/xxxFragment﹕ onPause
I/com.sjl.util.Foreground﹕ still foreground
V/GAV4﹕ Thread[GAThread,5,main]: Loaded clientId
D/xxxFragment﹕ onDetach
E/ViewRootImpl﹕ sendUserActionEvent() mView == null
```

Thanks...

P.S.: let me know if you need my image file for testing please

EDIT 1: for this is not relevant if image is zoom out or in in view component.

EDIT 2: btw this exception is catched for Exception in BitmapTileTask.doInBackground(), but OutOfMemory is not its child and because it is in async task it is not possible catch in my application. Please add catching OOM.

EDIT 3: hm, catching OOM is not recommended, e.g. http://stackoverflow.com/questions/1692230/is-it-possible-to-catch-out-of-memory-exception-in-java

**Comment by davemorrissey** [comment] 2015-03-09 16:02
On a phone with a very high resolution screen, the view may not tile the image because by default it loads image data at at least the same resolution as the screen. On the Note 3, with resolution 1920x1080, if the image is loaded in portrait orientation, it will need the whole image with sample size 1 to achieve this.
To rotate a bitmap, the view has to load the image, then create a new bitmap of the same size but rotated, and draw the original onto it. This means twice as much memory is briefly required while each tile is loaded.
One option is to change the minimumTileDpi figure so the view will load images at lower resolution and tile earlier. Something like 160 or 240dpi would normally be enough, compared to 386dpi for your screen.
Another option is to experiment with the attributes of the bitmap that gets created for rotation, because I think it may be ARGB_8888 and not RGB_565, so it requires twice as much memory.
I don't have an XXHDPI device so I've never been able to reproduce this.

**Comment by davemorrissey** [comment] 2015-03-09 18:01
There's another option, I'll try using a matrix to rotate tiles on draw. I had trouble making that work first time I tried, but then solved it for another part of the view. If it works that will eliminate the problem completely.

**Comment by davemorrissey** [comment] 2015-03-09 22:38
I've just pushed a fix as described - rotate the tiles on draw so there is no need to create a copy of each as it loads. I'm not ready to release this yet, are you able to verify the fix by cloning the repo and including it as a library project?

**Comment by PetrDana** [comment] 2015-03-10 08:23
Hi, thanks for fast fix. I download source code from master branch and update our project to using it (migration to 3.x). And it looks like it works! For older version of this view I apply "hot fix" by allow largeHeap, but your fix I tested with this disabled. So thank you very much :-)

When you suspect that this version will be stable for production?

P.S.: I noticed that in master is applied isBaseLayerReady() method with onImageLoaded event which I proposed in other issue, thanks ;-)

**Comment by davemorrissey** [comment] 2015-03-10 08:32
I've just uploaded a new release, v3.1.0. It may take a couple of hours for this to reach the central repository.

**Comment by davemorrissey** [comment] 2015-03-15 20:04
Unfortunately I've found that using a matrix to position tiles causes rounding errors resulting in intermittent black lines between tiles. I have rolled back this change, and as an interim fix I've limited tile size to 2048px, so you're unlikely to see OOMEs. I will experiment with rotating the canvas instead of using a matrix for each tile, but I needed to release the quickest possible fix.

**Comment by PetrDana** [comment] 2015-03-16 08:16
Thanks for info, I tested this new version and it is ok, there is no OOM on test images.

**Comment by davemorrissey** [comment] 2015-03-16 09:35
That's great, thanks. Canvas rotation is a dead end, but I'm having some early success using `Matrix.setPolyToPoly` for individual tiles - it virtually eliminates rounding errors - so once that's tested I can allow larger tiles again.

**Comment by davemorrissey** [comment] 2015-03-24 22:36
`Matrix.setPolyToPoly` works well. This has been released as v3.1.3, and the restriction on tile sizes removed.

**Closed by davemorrissey** 2015-03-24 22:36 UTC
Labels: bug

**Comment by Crni03** [comment] 2015-10-18 21:41
Hi
I'm having similar problem.
I'm using Your library in a Fragment and when i rotate images when slyding my app chrashes.
Couse Samsung devices save pictures rotated i have to rotate them back
Without rotating i can slyde as fast as I want.
This is how i'm loading images:
		        image.setOrientation(SubsamplingScaleImageView.ORIENTATION_90);
			image.setImage(ImageSource.uri(pathString));

To check rotation i'm using ExifInterface. 
Thanx!

**Comment by davemorrissey** [comment] 2015-10-21 12:59
Can you try using SubsamplingScaleImageView.ORIENTATION_USE_EXIF instead? The view now uses no more memory when images are rotated that it does with native orientation.

**Comment by Crni03** [comment] 2015-10-21 16:55
It rotates the pic but i still cant sylde images. 
It there a way to do this in SubsamplingScaleImageView class or in ImageSource class, or somewhere else?

**Comment by Crni03** [comment] 2015-10-28 08:58
So, is there any help for me or i'll hawe to find some other solutions? 
BTW, i still think that Your library is great, and i'm still useing it. When I put app on market, i'll let You know.

**Comment by davemorrissey** [comment] 2015-10-28 21:04
Sorry, I don't get much time to work on this. I've used over 20 images with a view pager in the sample app without any problems, no more than two images will normally be loaded at once because the view does not load tiles until it's on screen and has dimensions.

The view does not usually use any more memory to rotate the image than it does to show it in native orientation so I can't explain why you might have problems only when rotating the image.

I've assumed the crash your having is an OutOfMemoryError because you've reported it on this thread, but you haven't included a stack trace. Was it definitely an OOME and could you post the trace here please?

**Comment by Crni03** [comment] 2015-10-28 21:11
Hi! i was yust about to update my last comment. 

i did some kind of a workaround, when i rotate, and fragment destroys, i called onCreate method in on destroy method and it simply reloads the image again. Not the best solution, but it works!

It is OutOfMemoryError,

Here's log of a crash form eclipse


    10-28 21:00:24.835: E/AndroidRuntime(26400): FATAL EXCEPTION: AsyncTask #5
10-28 21:00:24.835: E/AndroidRuntime(26400): java.lang.RuntimeException: An error occured while executing doInBackground()
10-28 21:00:24.835: E/AndroidRuntime(26400): 	at android.os.AsyncTask$3.done(AsyncTask.java:299)
10-28 21:00:24.835: E/AndroidRuntime(26400): 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:352)
10-28 21:00:24.835: E/AndroidRuntime(26400): 	at java.util.concurrent.FutureTask.setException(FutureTask.java:219)
10-28 21:00:24.835: E/AndroidRuntime(26400): 	at java.util.concurrent.FutureTask.run(FutureTask.java:239)
10-28 21:00:24.835: E/AndroidRuntime(26400): 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:230)
10-28 21:00:24.835: E/AndroidRuntime(26400): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
10-28 21:00:24.835: E/AndroidRuntime(26400): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
10-28 21:00:24.835: E/AndroidRuntime(26400): 	at java.lang.Thread.run(Thread.java:841)
10-28 21:00:24.835: E/AndroidRuntime(26400): Caused by: java.lang.OutOfMemoryError
10-28 21:00:24.835: E/AndroidRuntime(26400): 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
10-28 21:00:24.835: E/AndroidRuntime(26400): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:623)
10-28 21:00:24.835: E/AndroidRuntime(26400): 	at android.graphics.BitmapFactory.decodeFile(BitmapFactory.java:378)
10-28 21:00:24.835: E/AndroidRuntime(26400): 	at com.davemorrissey.labs.subscaleview.decoder.SkiaImageDecoder.decode(SkiaImageDecoder.java:61)
10-28 21:00:24.835: E/AndroidRuntime(26400): 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1556)
10-28 21:00:24.835: E/AndroidRuntime(26400): 	at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$BitmapLoadTask.doInBackground(SubsamplingScaleImageView.java:1)
10-28 21:00:24.835: E/AndroidRuntime(26400): 	at android.os.AsyncTask$2.call(AsyncTask.java:287)
10-28 21:00:24.835: E/AndroidRuntime(26400): 	at java.util.concurrent.FutureTask.run(FutureTask.java:234)
10-28 21:00:24.835: E/AndroidRuntime(26400): 	... 4 more

**Comment by davemorrissey** [comment] 2015-10-28 21:19
I assume you mean when you rotate the screen portrait to landscape it destroys the fragment, and you're not talking about rotating the image? If what you've described is your way of avoiding that, it sounds very likely that it will result in multiple images being loaded at once. I'm not sure I understand what you're trying to achieve.

**Comment by Crni03** [comment] 2015-10-28 21:24
The problem is that Samsung phones rotate images whan capturaing. 
So, when i show them in my gallery, they are oriented wrong. 
screen rotation does not crash, slydeing images does, it just freezes PageFragment and chashes it. 
If you would like, i could mail You my SyldeActivity and PageFragment?

**Comment by davemorrissey** [comment] 2015-10-28 21:27
But if you're calling the fragment's onCreate method from its onDestroy method as you said above to fix some problem with screen orientation changes, that will also be happening as Android is trying to destroy pages in your pager when you go to other pages, and that may prevent it garbage collecting views that are no longer on screen.

**Comment by Crni03** [comment] 2015-10-28 21:31
I removed onDestroy.
The crash is not happening when i rotate the phone, it happens when i slyde images

**Comment by davemorrissey** [comment] 2015-10-28 21:32
Send me the code.

**Comment by Crni03** [comment] 2015-10-28 21:33
ok. I found no mail adress so You can here's mine. 
vjeko03@gmail.com
