### ISSUE TITLE
How to getBitmap from the PinView?

### ISSUE THREAD

**Issue by ashwini009** [davemorrissey/subsampling-scale-image-view#276] opened 2016-12-08 13:58 UTC
I have PinView on the layout where I have set an ImageSource. I want to get the BitMap from it. Please help

**Comment by davemorrissey** [comment] 2016-12-20 10:58
Duplicate of #19, #57, #104, #196, #264. Please check closed issues before raising a new one! Answers also available on StackOverflow.

**Closed by davemorrissey** 2016-12-20 10:58 UTC
