### ISSUE TITLE
Why can't use at Tablet Screen Size?

### ISSUE THREAD

**Issue by PeterPhyo** [davemorrissey/subsampling-scale-image-view#292] opened 2017-02-20 03:41 UTC
I can't use, touch zoom in & zoom out at tablet screen size. It doesn't work. Why?

**Comment by davemorrissey** [comment] 2017-02-20 16:09
Duplicate of #251 and others. Please search closed issues before raising a new one.

**Closed by davemorrissey** 2017-02-20 16:09 UTC
