### ISSUE TITLE
prevent long click and double tap event to trigger for the same event

### ISSUE THREAD

**Issue by hgourvest** [davemorrissey/subsampling-scale-image-view#267] opened 2016-11-21 10:40 UTC
```
if (message.what == MESSAGE_LONG_CLICK && onLongClickListener != null) {
                    maxTouchCount = 0;
                    SubsamplingScaleImageView.super.setOnLongClickListener(onLongClickListener);
                    if (performLongClick())
                             isQuickScaling = false; <<<<<<<<<
                    SubsamplingScaleImageView.super.setOnLongClickListener(null);
}
```

**Comment by davemorrissey** [comment] 2016-11-21 18:39
Please can you explain the problem and how this change fixes it?

**Comment by hgourvest** [comment] 2016-11-21 18:54
when you double tap and keep your finger at the same place without moving, it is interpreted as a long press event when you remove the finger, but during this time the quick scaling mode was also activated and removing the finger also trigger the double tap event just after the long press event (line 854). My fix detect if a long press event was really handled, and cancel the double tap if necessary.

**Comment by davemorrissey** [comment] 2016-11-21 19:09
Great, thanks for the explanation. I'll try out this fix.

**Comment by davemorrissey** [comment] 2017-04-04 09:52
I haven't been able to make the view trigger both a long press event and a double tap zoom event on the same gesture as you've described. On every double tap, regardless of how long I keep my finger on the screen on the second tap, it's interpreted as a double tap zoom (or a quick scale zoom if I move my finger). There is no long press event. Are you still seeing this problem? Is it specific to a device or Android version?

**Comment by hgourvest** [comment] 2017-04-07 22:35
I was using a Oneplus2 device with Android 6.0.1, unfortunately your project don't fit my needs, so I no longer using it. Sorry.

**Comment by davemorrissey** [comment] 2017-04-08 07:14
Okay thanks, as I can't reproduce this myself I'll close this until someone else does.

**Closed by davemorrissey** 2017-04-08 07:14 UTC
