### ISSUE TITLE
Panning - Allow panning to point on screen

### ISSUE THREAD

**Issue by MFlisar** [davemorrissey/subsampling-scale-image-view#163] opened 2015-12-15 18:16 UTC
I want to use the view as a base for a fixed size window crop view. Therefore I use my crop overlay on top of your view. The crop overlay does not fill the screen but an custom area on the screen. So I would like to allow panning the image not only in the SSIV bounds but further so that i can pan the image to have it's border underneath the overlay boder.

Is that somehow possible? I think it isn't. Any idea for a trick to achieve that?

**Comment by davemorrissey** [comment] 2015-12-16 07:17
Duplicate of #144 - the last comment there should provide an answer.

**Closed by davemorrissey** 2015-12-16 07:17 UTC

**Comment by MFlisar** [comment] 2015-12-18 15:10
Could you make the function protected in your library? It's easier to keep up to date then if I don't have to use my own copy of your library...

**Comment by davemorrissey** [comment] 2015-12-18 20:14
I don't really want to start opening up all the methods, especially that one which is critical to the proper behaviour. It's better to fork the library if you want to make changes as fundamental as this. One day I might get around to adding a custom pan limit but sadly I'm too busy to work on this library at the moment :-(
