### ISSUE TITLE
Padding for behind a toolbar

### ISSUE THREAD

**Issue by Floens** [davemorrissey/subsampling-scale-image-view#77] opened 2015-05-27 18:03 UTC
This issue is relevant to #39 

I want to set a padding to the ssiv, so that it reserves space for a toolbar, but it should fall behind the toolbar when zoomed in.

When using the following layout
```
<FrameLayout
    android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView
        android:id="@+id/image"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:paddingTop="56dp" />

    <TextView
        android:id="@+id/toolbar"
        android:layout_width="match_parent"
        android:layout_height="56dp" />

</FrameLayout>'
```

I get the following results:
![horizontal](https://cloud.githubusercontent.com/assets/1012578/7843518/60a9d58a-04aa-11e5-8597-396e5f7a9247.png)

![vertical](https://cloud.githubusercontent.com/assets/1012578/7843523/66fbe37e-04aa-11e5-9007-b58c50b803e9.png)

As you can see the vertical image works fine but the horizontal image moves to the bottom, instead I want it centered vertically. The images do go behind the toolbar correctly when zoomed.

Is this intended behavior or is this a bug?

Thanks in advance.

**Comment by davemorrissey** [comment] 2015-05-27 18:20
That's the intended behaviour. If the padding is asymmetric, the view preserves the top:bottom and left:right padding ratios as you zoom in, so in this case, because you have no bottom padding, the image remains flush with the bottom until it becomes larger than the screen. I didn't really intend the view to be used with asymmetric padding, and this seemed to be the best option at the time.

Maybe you could detect whether the image has a greater width:height ratio than the space available in the view, and add bottom padding if so.

**Comment by Floens** [comment] 2015-05-27 18:25
Thank you for your response, I'll try to see if I can do something with the padding.

**Comment by davemorrissey** [comment] 2015-06-04 19:39
I'll close this because it's intended behaviour but if you find a workaround it would be interesting to see how you did it.

**Closed by davemorrissey** 2015-06-04 19:39 UTC
