### ISSUE TITLE
Not compatible with libraries that expect ImageView

### ISSUE THREAD

**Issue by mhousser** [davemorrissey/subsampling-scale-image-view#112] opened 2015-09-02 22:00 UTC
Surprised to see that this does not extend ```ImageView```. Image loading via libraries such as Picasso is ruined because this component extends ```View```. Other such libraries extend ```ImageView``` so as to play nicely with everything else. As such, I can't see this as a viable option, which is a shame since it appears to be under active development..

Is there a reason that ```ImageView``` isn't the base for ```SubsamplingScaleImageView```?

**Comment by davemorrissey** [comment] 2015-09-03 04:25
Duplicate of #81, #100

**Closed by davemorrissey** 2015-09-03 04:25 UTC

**Comment by mhousser** [comment] 2015-09-03 04:26
Unfortunate. Will not recommend this library.

**Comment by davemorrissey** [comment] 2015-09-03 04:31
Image loaders are designed to load a Bitmap from some source and pass them to an ImageView. SubsamplingScaleImageView is designed to display images that are too large to be loaded in this way, so their aims are not compatible.

**Comment by gokhanbarisaker** [comment] 2015-09-03 09:40
Here is a way to use SubsamplingScaleImageView with decoder and region decoder,

  https://gist.github.com/gokhanbarisaker/c116bea7fc10e6eac25d


Make sure 
  - Your OkHttp client is using a disk cache
  - You are calling picasso.cancelTag(tagYouUsedInDecoderConstructor), when you are done with the image. e.g., Fragment/Activity onDestroy callback

**Comment by davemorrissey** [comment] 2015-09-03 09:58
Very nice! Do you mind if I add that to the wiki? One minor point - using ARGB_8888 makes it a lot more likely the view will run out of memory on low powered devices.

**Comment by gokhanbarisaker** [comment] 2015-09-03 10:14
Please do. I was thinking of contacting with you for that. I already owe you for this library :)

The ARGB_8888 is essential in my app for the color changes needs to be smooth. In this case, changing the default value to RGB_565 might be wiser, as in your other decoder examples

**Comment by KingWu** [comment] 2015-10-04 18:00
@gokhanbarisaker Any example show how to use these decoder and region decoder? I got this error

10-05 01:51:09.066    4128-4192/com.votee.dev E/SubsamplingScaleImageView﹕ Failed to initialise bitmap decoder
    java.lang.InstantiationException: class com.votee.core.util.zoom.PicassoRegionDecoder has no zero argument constructor
            at java.lang.Class.newInstance(Class.java:1597)
            at com.davemorrissey.labs.subscaleview.decoder.CompatDecoderFactory.make(CompatDecoderFactory.java:18)
            at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1399)
            at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1376)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)
     Caused by: java.lang.NoSuchMethodException: <init> []
            at java.lang.Class.getConstructor(Class.java:531)
            at java.lang.Class.getDeclaredConstructor(Class.java:510)
            at java.lang.Class.newInstance(Class.java:1595)
            at com.davemorrissey.labs.subscaleview.decoder.CompatDecoderFactory.make(CompatDecoderFactory.java:18)
            at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1399)
            at com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView$TilesInitTask.doInBackground(SubsamplingScaleImageView.java:1376)
            at android.os.AsyncTask$2.call(AsyncTask.java:292)
            at java.util.concurrent.FutureTask.run(FutureTask.java:237)
            at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
            at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
            at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
            at java.lang.Thread.run(Thread.java:818)

**Comment by gokhanbarisaker** [comment] 2015-10-05 08:11
@KingWu, [setBitmapDecoderClass(...)](https://github.com/davemorrissey/subsampling-scale-image-view/blob/master/library/src/com/davemorrissey/labs/subscaleview/SubsamplingScaleImageView.java#L2083)  and [setRegionDecoderClass(...)](https://github.com/davemorrissey/subsampling-scale-image-view/blob/master/library/src/com/davemorrissey/labs/subscaleview/SubsamplingScaleImageView.java#L2057) methods uses
[CompatDecoderFactory](https://github.com/davemorrissey/subsampling-scale-image-view/blob/master/library/src/com/davemorrissey/labs/subscaleview/decoder/CompatDecoderFactory.java) to initialize new instances of `BitmapDecoder` and `RegionDecoder`. In your case you will need to replace constructor with default (empty) version. i.e.,

``` java
public PicassoRegionDecoder () {
    // TODO: Don't forget to initialize OkHttpClient instance during init method call, or (even better) use your singleton OkHttpClient instance for application.
    /**
     * See [response caching paragraph #2](https://github.com/square/okhttp/wiki/Recipes#response-caching) for why singleton client usage is better.
     *
     * "Most applications should call new OkHttpClient() exactly once, configure it with their cache, 
     * and use that same instance everywhere. Otherwise the two cache instances will stomp on 
     * each other, corrupt the response cache, and possibly crash your program."
     */
}
```

As an alternative, you can initialize your custom [DecoderFactory](https://github.com/davemorrissey/subsampling-scale-image-view/blob/master/library/src/com/davemorrissey/labs/subscaleview/decoder/DecoderFactory.java)
