### ISSUE TITLE
Wrong image scaling after v.setMargins

### ISSUE THREAD

**Issue by qstra** [davemorrissey/subsampling-scale-image-view#268] opened 2016-11-21 11:17 UTC
Hi, I have a problem with scaling images that uses PhotoViewAttacher.

I published the video so you know what I mean. (Adding picture frames by setting the margin), with PhotoViewAttacher leave frame of white space, the picture may not match up to the original size, even after reloading images.

[https://www.youtube.com/watch?v=kKyyxQHi0Sc](https://www.youtube.com/watch?v=kKyyxQHi0Sc)

and:

[https://youtu.be/IDFcdRuEAN0?t=16](https://youtu.be/IDFcdRuEAN0?t=16) (0:16)

This is how i use margins for creating images border:

`  for (ImageView view : imageViewsToFillWithPhotos) {
                    FrameLayout.LayoutParams margins = new FrameLayout.LayoutParams(view.getLayoutParams());
                    margins.setMargins((int) thinBorderSize, (int) thinBorderSize, (int) thinBorderSize, (int) thinBorderSize);
                    view.setLayoutParams(margins);
                }`

How can I avoid this? I tried without attaching images and it works 100% fine. 

The worst part is that there is no strict script error. And he appears when he wants to.

Also im using Glide with CenterCrop for load imgs.

**Comment by davemorrissey** [comment] 2016-11-21 18:50
Duplicate of #82 #155. Please extend the class to implement `onSizeChanged` as you need it.

**Closed by davemorrissey** 2016-11-21 18:50 UTC
