### ISSUE TITLE
Does not handle local URIs with spaces

### ISSUE THREAD

**Issue by samskiter** [davemorrissey/subsampling-scale-image-view#114] opened 2015-09-11 13:54 UTC
The library seems not to work for me for images that have spaces in their file names (and are therefore URI encoded). I think I've tracked this to the following line: https://github.com/davemorrissey/subsampling-scale-image-view/blob/master/library/src/com/davemorrissey/labs/subscaleview/decoder/SkiaImageRegionDecoder.java#L61

If this were instead:

```
ContentResolver contentResolver = context.getContentResolver();
decoder = BitmapRegionDecoder.newInstance(contentResolver.openInputStream(Uri.parse(uriString.substring(FILE_PREFIX.length()))), false);
```

I think there would be no issue.

**Comment by samskiter** [comment] 2015-09-11 14:08
Just confirmed the issue is URL encoding by passing a the URI as a string to ImageSource, but using URLDecoder beforehand.

**Comment by samskiter** [comment] 2015-09-11 14:14
PR: https://github.com/davemorrissey/subsampling-scale-image-view/pull/115

**Comment by Uscher1** [comment] 2015-09-21 13:25
Same problem here. Please apply PR.

**Comment by davemorrissey** [comment] 2015-09-24 20:04
I can't reproduce this at the moment. This works:

    imageView.setImage(ImageSource.uri("file://sdcard/DCIM/IMAG 0210.jpg"));

This also works:

    imageView.setImage(ImageSource.uri(Uri.parse("file://sdcard/DCIM/IMAG 0210.jpg")));

Your suggested in PR #115 breaks both of these cases. Could you provide some sample code I could use to reproduce the problem you're seeing?

**Comment by samskiter** [comment] 2015-09-25 01:29
Right, so I think the issue is that android can return a URI with URI encoding in it.

The chain of events to arrive at this situation was to iterate files in a directory and form a URI like this:

`Uri.fromFile(file)`

Which results in something like:

`file:///storage/emulated/0/Pictures/MyApplication/My%20Image.jpg`  which is why I tried to make sure Uri.parse was called on the string.

So the actual problem here is that file URI's need to be decoded as URI encoded objects...

Also worth noting, the same URI worked fine with the Glide framework... I'm not sure what they do differently.

**Comment by davemorrissey** [comment] 2015-09-25 07:34
I've tried to find a workaround for this, but the difficulty is that the view has no way of knowing whether the URI string it's given is URL encoded, or just contains %xx escape sequences deliberately. Only the app code will know that, based on how it generated the URI. The app code can use `URLDecoder.decode` to decode the URI if it's from `Uri.fromFile` or any other source that encodes the URI.

Supposing my file is named `Imag 001.jpg` and I use `Uri.fromFile` to get the URI, it will be encoded to `Image%20001.jpg`. Now if I have a file named `Imag%20001.jpg` (unlikely I know) and I use some method that doesn't encode it, the view can't distinguish between them and whatever fix I put in for one will break the other.

I think it will have to be the app developer's responsibility to check whether their URLs are getting encoded, and decode them if necessary.

**Comment by samskiter** [comment] 2015-09-25 11:05
Hmmm, so maybe I need to do a test with Glide with an image named `Imag%20001.jpg` and loaded differently. I suppose it assumes that all URIs must be URI encoded.

**Comment by davemorrissey** [comment] 2015-09-25 19:05
Let me know what you discover. I don't have much time to set up test projects with other libraries like this, but if there's a fix I can add without breaking anything for existing users I'll do it.

**Comment by davemorrissey** [comment] 2015-09-30 18:55
I've put in a workaround for `Uri.fromFile` URL encoding the path. The ImageSource constructor will check whether the file exists, and if not it will URL decode the path and try again. This works for `Uri.fromFile` provided the path you used in the `File` constructor was not URL encoded, because `Url.fromFile` would then double encode it. This will be in the next release.

**Closed by davemorrissey** 2015-09-30 18:55 UTC

**Comment by riyase** [comment] 2015-11-25 11:44
does this have a solution? still i can't access files with "space" in it.
