### ISSUE TITLE
Allow zoom, even when image is small?

### ISSUE THREAD

**Issue by ParkerK** [davemorrissey/subsampling-scale-image-view#422] opened 2018-05-04 17:34 UTC
Is it possible to force SSIV to allow zooming on images that are smaller than the screen? Or some way to further the zoom amount possible? I understand resolution will decrease as it zooms, but I'd still like to enable it if possible.

### Expected behaviour
You should be able to pinch to zoom (or zoom in any way) on an image of any size

### Actual behaviour
Images that are smaller than the screen size, do not allow zooming

### Steps to reproduce
Load a small image, and try to zoom

### Affected devices
N/A

### Affected images
Not applicable

**Comment by davemorrissey** [comment] 2018-05-04 18:03
Duplicate of #251. Please read the wiki and past issues before opening new ones.

**Closed by davemorrissey** 2018-05-04 18:03 UTC
