### ISSUE TITLE
Exception java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap

### ISSUE THREAD

**Issue by pralatto** [davemorrissey/subsampling-scale-image-view#288] opened 2017-01-23 18:26 UTC
hi, i've had a problem, maybe is it a failure with this lib?:

android.graphics.Canvas.throwIfCannotDraw (Canvas.java:1282)
android.view.GLES20Canvas.drawBitmap (GLES20Canvas.java:589)
**com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView.onDraw (SubsamplingScaleImageView.java:1073)**
android.view.View.draw (View.java:15321)
android.view.View.updateDisplayListIfDirty (View.java:14257)
android.view.View.getDisplayList (View.java:14279)
android.view.View.draw (View.java:15049)
android.view.ViewGroup.drawChild (ViewGroup.java:3406)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3199)
android.view.View.draw (View.java:15324)
android.view.View.updateDisplayListIfDirty (View.java:14257)
android.view.View.getDisplayList (View.java:14279)
android.view.View.draw (View.java:15049)
android.view.ViewGroup.drawChild (ViewGroup.java:3406)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3199)
android.view.View.updateDisplayListIfDirty (View.java:14252)
android.view.View.getDisplayList (View.java:14279)
android.view.View.draw (View.java:15049)
android.view.ViewGroup.drawChild (ViewGroup.java:3406)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3199)
android.view.View.updateDisplayListIfDirty (View.java:14252)
android.view.View.getDisplayList (View.java:14279)
android.view.View.draw (View.java:15049)
android.view.ViewGroup.drawChild (ViewGroup.java:3406)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3199)
android.view.View.updateDisplayListIfDirty (View.java:14252)
android.view.View.getDisplayList (View.java:14279)
android.view.View.draw (View.java:15049)
android.view.ViewGroup.drawChild (ViewGroup.java:3406)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3199)
android.view.View.updateDisplayListIfDirty (View.java:14252)
android.view.View.getDisplayList (View.java:14279)
android.view.View.draw (View.java:15049)
android.view.ViewGroup.drawChild (ViewGroup.java:3406)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3199)
android.view.View.updateDisplayListIfDirty (View.java:14252)
android.view.View.getDisplayList (View.java:14279)
android.view.View.draw (View.java:15049)
android.view.ViewGroup.drawChild (ViewGroup.java:3406)
android.view.ViewGroup.dispatchDraw (ViewGroup.java:3199)
android.view.View.draw (View.java:15324)
android.widget.FrameLayout.draw (FrameLayout.java:598)
com.android.internal.policy.impl.PhoneWindow$DecorView.draw (PhoneWindow.java:2653)
android.view.View.updateDisplayListIfDirty (View.java:14257)
android.view.View.getDisplayList (View.java:14279)
android.view.ThreadedRenderer.updateViewTreeDisplayList (ThreadedRenderer.java:273)
android.view.ThreadedRenderer.updateRootDisplayList (ThreadedRenderer.java:279)
android.view.ThreadedRenderer.draw (ThreadedRenderer.java:318)
android.view.ViewRootImpl.draw (ViewRootImpl.java:2540)
android.view.ViewRootImpl.performDraw (ViewRootImpl.java:2356)
android.view.ViewRootImpl.performTraversals (ViewRootImpl.java:1986)
android.view.ViewRootImpl.doTraversal (ViewRootImpl.java:1065)
android.view.ViewRootImpl$TraversalRunnable.run (ViewRootImpl.java:5901)
android.view.Choreographer$CallbackRecord.run (Choreographer.java:767)
android.view.Choreographer.doCallbacks (Choreographer.java:580)
android.view.Choreographer.doFrame (Choreographer.java:550)
android.view.Choreographer$FrameDisplayEventReceiver.run (Choreographer.java:753)
android.os.Handler.handleCallback (Handler.java:739)
android.os.Handler.dispatchMessage (Handler.java:95)
android.os.Looper.loop (Looper.java:211)

(Android 5.1.1, sony c6903)

I'm not sure what is at fault, have you any idea?
thx :)

**Comment by davemorrissey** [comment] 2017-01-23 21:17
Duplicate of #213

**Closed by davemorrissey** 2017-01-23 21:17 UTC
