### ISSUE TITLE
How to use with ListView?

### ISSUE THREAD

**Issue by alejandrolagosr** [davemorrissey/subsampling-scale-image-view#303] opened 2017-03-16 03:22 UTC
I'm loading a set of images in a ListView, those 800x200 images work well with the setOnItemClickListener event, but when I started using this awesome library I could not catch the ItemClickListener. It is possible to make it work? 

This is my ListView item click listener:
```
        lvPrenda.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                fm = getChildFragmentManager();
                int subcategoryId = adapter.get(position).getSubcategoryId();
                String subcategoryName = adapter.get(position).getSubcategoryName();

                Fragment newFragment = SubcategoryFragment.newInstance(subcategoryId,
                        subcategoryName, sexInt);

                FragmentTransaction transaction = getChildFragmentManager().beginTransaction();
                transaction.setCustomAnimations(R.anim.enter_from_right, R.anim.exit_to_left, R.anim.enter_from_left, R.anim.exit_to_right);
                transaction.replace(R.id.prenda, newFragment);
                transaction.addToBackStack("prd");
                transaction.commit();
            }
        });
```
and I'm using this as holder:

```
public class Adapter_Prenda extends ArrayAdapter<SubcategoryItem> {
    Context cn;

    public Adapter_Prenda(Context context, ArrayList<SubcategoryItem> users) {
        super(context, R.layout.adapter_search_subcategory, users);
        this.cn=context;
    }

    @Override
    public View getView(int position, View convertView2, ViewGroup parent) {
        // Get the data item for this position
        SubcategoryItem model = getItem(position);

        LayoutInflater inflater = (LayoutInflater) cn.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
        View convertView = inflater.inflate(R.layout.adapter_search_subcategory, parent, false);
        ((SubsamplingScaleImageView) convertView.findViewById(R.id.imgPrendaExt)).setImage
                (ImageSource.resource(model.getPrenda()).tilingDisabled());
        
        // Return the completed view to render on screen
        return convertView;
    }
}

```

**Comment by davemorrissey** [comment] 2017-07-27 09:35
I'm sorry I didn't really have an answer for this, I don't have a lot of time to build sample apps and experiment with solutions. Did you find a fix?

**Comment by davemorrissey** [comment] 2017-11-09 14:44
Unclear what the problem is and what's been tried to resolve it. Closing.

**Closed by davemorrissey** 2017-11-09 14:44 UTC
Labels: question
