### ISSUE TITLE
Image Zoom Blurry in Some Parts of the Image

### ISSUE THREAD

**Issue by avp2306** [davemorrissey/subsampling-scale-image-view#55] opened 2015-03-15 00:54 UTC
Hello - reaching out with an odd issue that I have a hard time reproducing. A number of my users are reporting that when they zoom in on some parts of the image, it just stays blurry and never clears up.

What I mean by that is, whenever you zoom in on an image, its a bit blurry at first but then clears up as the processing takes place. With these reports users are saying that in certain areas of the image always stay blurry on zoom no matter how long they wait. But other parts of the image are ok.

From what I see this is on Samsung devices, a number of reports are from Galaxy S5.

This is a bit odd as I never saw anything like this in my own testing with 15 devices. Have you experienced anything similar, and if so how to best tackle this issue?

Thanks!

**Comment by davemorrissey** [comment] 2015-03-15 07:22
Hi, can you let me know which version of the library you're seeing problems with, and attach the image?

I have one idea for what could cause this, but it would only make sense if it's the right and bottom edges of the image that are staying blurry.

**Comment by davemorrissey** [comment] 2015-03-15 09:48
I've just fixed a potential problem with images close to a multiple of the canvas max bitmap size, but I don't think this is the cause of your problem, because that would cause areas to go black, not blurry.

The more you can tell me about this problem the better, so if you can send me a link to your app, the image (is it just one?), your code etc. that would help.

**Comment by avp2306** [comment] 2015-03-16 04:51
Hi Dave - and again, much thanks for your prompt reply.

The problem is as you described, effected areas are right and bottom sides of the image. I'm not able to get my hands on a screenshot as I'm not able to repro the issue myself - so going by user reports only. 

Also, I have increased the size of the image I'm showing in the last app update - after that problem reports started coming in. Image went from 2MB to ~3MB. Its a transit map with dimensions of about 5000 x 4500 px. I dont believe image has transparencies. Its a PNG 24 format.

Regarding devices: so far I only saw it from users reporting Samsung devices, but ranging from new Galaxy S5 running Lollipop to really old SGH models running Gingerbread 2.3.6. I got 3 Samsung devices myself - however unable to repro this at all.

I have 2 images (maps), that I display 1 at a time using a single UI control. User hits a button to swap the image where I alternate between file names calling :

_imgMap.setImageAsset("file1.png")

Please feel free to let me know if any more info would be useful to help diagnose this. I think thats all that I can think of.

Thanks,
-Alex

**Comment by davemorrissey** [comment] 2015-03-16 06:44
I'm afraid I don't really have any ideas. The latest version should fix a possible issue if the image was a few pixels either side of 4096px but it doesn't sound like your image is, and as I said before it would cause black areas, not blurry. It's worth a try though.

The only thing I can suggest is to use the OnImageEventListener to log tile loading errors and somehow get logcat from an affected user. Areas remaining blurry suggests tiles are failing to load.

**Comment by avp2306** [comment] 2015-03-16 07:07
Logging is always a good idea, do I just attach that to the image control ?

Also, do you think its possible that the image settings could have anything to do with it? I just double checked and I think I saved it as PNG 8 with reduced color settings.

Another thought, how about positioning of the image control itself, I have it inside relative layout with FILL_PARENT for both width & height.

Just throwing some ideas out there. This would be a lot easier if I could reproduce this issue.

**Comment by davemorrissey** [comment] 2015-03-16 07:17
Yes, use the `setOnImageEventListener` method. The tricky bit is getting logs from a user but I think there are various solutions for that, I haven't looked recently.

Image settings could cause it, but that seems unlikely if the rest of the image is decoded properly, and I have used indexed images before. You could try using a full RGB PNG with no alpha layer. You could also try changing the size slightly, or using the RapidImageRegionDecoder class from the sample library, which uses libpng instead of skia.

Make sure you upgrade to 3.1.2 as well. Another point fix is coming soon to solve another small and unrelated problem. Are you rotating the image or displaying it in its native orientation?

Position of the view is very unlikely to be the cause and you seem to have it set up the usual way.

**Comment by avp2306** [comment] 2015-03-16 07:21
Thanks, I'll try attaching the listener to see what I can grab from within that event. I'm also in contact with a user that is having this problem - so at least have a way to test this.

I do rotate the image, and on rotation the layout changes as well - I basically hide everything on the screen including action bar to show the map in complete full screen whenever device is in landscape mode.

**Comment by avp2306** [comment] 2015-03-16 20:15
Hi Dave - so I got some feedback to share, the end user I'm working with was able to get back to me.

I tried to re-save the image as PNG 8 using different color settings but that had no effect. PNG 24 has a high file size so I wanted to try 8 bit first. This had no effect on the issue. 

I've added logging to setOnImageEventListener - but results will take some time to post as I'm using Google Analytics for exception logging.

At this point I think I have the following additional options to try:
- Try with PNG-24
- Try with JPEG
- Try with RapidImageRegionDecoder

Please feel free to add any additional things I should try, I'm going to include a small test harness in the dev build for the user I'm working with which will have a pop-up allowing to test multiple fixes - this way he can try multiple things at once and get back to me. 

User also provided me screenshots, sharing those with you as well. Please see attached:
![screenshot_2015-03-16-12-14-20](https://cloud.githubusercontent.com/assets/1009154/6675327/07467710-cbf6-11e4-99d3-48799b8a8cdb.png)
![screenshot_2015-03-16-12-14-57](https://cloud.githubusercontent.com/assets/1009154/6675331/08d4152e-cbf6-11e4-9b96-44a70e7df4af.png)
![screenshot_2015-03-16-12-15-23](https://cloud.githubusercontent.com/assets/1009154/6675337/0d0363a2-cbf6-11e4-9ebe-915093e28c57.png)

Thank you for your assistance with this, and for your dedication to this library.

-Alex

**Comment by davemorrissey** [comment] 2015-03-16 20:38
Hi Alex, the released version of your app appears to be using v2.3.0 at the latest, could you try v3.1.2 as well?

**Comment by avp2306** [comment] 2015-03-16 20:41
Hi Dave - I forgot to mention this but I also updated the library in this build as well. So this is actually using 3.1.2: http://screencast.com/t/GXlnnDp6

Thanks.

**Comment by davemorrissey** [comment] 2015-03-16 20:44
That's interesting, I guess this must have always been an issue. I thought I might have introduced it in the 3.x releases which have had major changes. It also eliminates all the possibilities I can think of, because I've fixed all of them already and I'm confident 2.x was pretty stable.

**Comment by avp2306** [comment] 2015-03-16 20:58
Thanks. I'll try the 3 options above and report my findings, I have a feeling playing around with image formats may do it.

**Comment by davemorrissey** [comment] 2015-03-16 21:17
Can I just double check - do you know which version of the library you were using when this problem was first spotted? Do you think it appeared in a particular version or has been there since you started using it?

**Comment by avp2306** [comment] 2015-03-16 21:46
Sure. I believe this was happening in both versions. My current prod version of the app has the older version. And the dev build I'm testing with the end user is the new latest version.

**Comment by davemorrissey** [comment] 2015-03-16 21:49
What was the older version? 2.3.0?

**Comment by avp2306** [comment] 2015-03-16 22:12
Yep, it was 2.3.0

**Comment by avp2306** [comment] 2015-03-18 09:48
Hi Dave - good news.

Well kinda :) but I finally am able to reproduce this consistently on one of my test devices, this time its a Nexus 5 L 5.1. After playing around with file formats I get the same issue in the same regions of the image when saving the image as PNG-24 (~6mb file size). However the same file works fine on Galaxy S3. 

So I really feel its a memory management issue or the decoder itself uses some very low level OS API that is different base on model & manufacturer. 

JPEG format seems to be working fine - so that's what I'll go with for the moment. 

I also wasn't able to get the RapidImageRegionDecoder to work, I would get the following error:
E/SubsamplingScaleImageView﹕ Failed to initialise bitmap decoder
    java.lang.InstantiationException: class com.nyctrans.it.MapActivity$RapidImageRegionDecoder has no zero argument constructor

I'm using the following code to set the image:
_imgMap = (com.davemorrissey.labs.subscaleview.SubsamplingScaleImageView) findViewById(R.id.imgScaledImageViewMap);
_imgMap.setRegionDecoderClass(RapidImageRegionDecoder.class);
_imgMap.setDoubleTapZoomDpi(200);
_imgMap.setMinimumTileDpi(160);
_imgMap.setImage(ImageSource.asset("map_png24.png")

I'm using this class from the examples project:
https://github.com/davemorrissey/subsampling-scale-image-view/blob/master/sample/src/com/davemorrissey/labs/subscaleview/sample/imagedisplay/decoders/RapidImageRegionDecoder.java

I created the same class and added a default constuctor but still was getting the same error. I feel like I missed something obvious.

Anyways, thought I'd share some details from my end, hope this is useful.

I'm going to test the JPEG approach using the default decoder and I'll follow up with results shortly.

Thanks.

**Comment by davemorrissey** [comment] 2015-03-18 09:58
I'll digest this properly later (I'm at work!) but the only obvious thing I can think of with the default constructor is that you made the decoder class a non-static inner class, and maybe didn't remove it when you tried a separate file. If you make it static or put it in its own file it should work. Make sure you include all the dependencies in the gradle file - see the sample app.

If it was a memory management problem in the view you'd see a pretty obvious error. It's more likely to be skia, which is very fragile and varies as you say.

For this kind of image, it's obviously preferable to stick with PNG if you can!

**Comment by avp2306** [comment] 2015-03-18 10:43
Yay, making it static got rid of the exception, but blurriness is still there with PNG files.

Looking through the logs, I also found this, not a problem as I will use JPEG for now, but thought I'd mention it.
skia﹕ --- decoder->decodeRegion returned false

I'll test it with my end user and post results - keeping fingers crossed :)

Thanks.

**Comment by davemorrissey** [comment] 2015-03-18 10:57
I would just double check you included all the dependencies below when you tried a PNG with RapidImageRegionDecoder, because if you saw that skia error then it isn't using libpng.

compile 'rapid.decoder:library:0.3.0'
compile 'rapid.decoder:jpeg-decoder:0.3.0'
compile 'rapid.decoder:png-decoder:0.3.0'

The skia error does prove it was failing to decode the tiles (which I was sure of anyway). One slight possibility is that the view is calculating tile boundaries slightly outside the actual size of the image, which doesn't seem to cause problems normally but maybe it does with specific image encodings. You could try logging the tile sRects to see if they are correct.

BTW don't use rapid decoder with JPGs, as you'll see it's very slow.

**Comment by davemorrissey** [comment] 2015-03-24 07:26
Did you make any more progress with this? Have you concluded it was a problem with that particular image?

**Comment by avp2306** [comment] 2015-03-24 07:34
Hi Dave - thanks for following up.

The user I was testing with reported positive results, so I went ahead and released it to the public - so far so good. I'm going to keep an eye out for user reports and let you know if any issues come up.

Thanks for your help!

**Comment by davemorrissey** [comment] 2015-03-31 20:54
Closing because it looks like this is a decoding problem that can't be fixed in the view. If any other info becomes available keep adding comments.

**Closed by davemorrissey** 2015-03-31 20:54 UTC
