### ISSUE TITLE
Universal Image Loader DisplayImage problem

### ISSUE THREAD

**Issue by loscabres** [davemorrissey/subsampling-scale-image-view#146] opened 2015-11-08 12:31 UTC
Hi,

I use the Universal Image Loader lib
I try to use the displayImage property, I need the second parameter be the ImageView or ImageAware, how I can get this object from the SubSampling Scale Image View?

thank you

**Comment by davemorrissey** [comment] 2015-11-08 12:42
Duplicate of #45, #81, #100, #112

**Closed by davemorrissey** 2015-11-08 12:42 UTC
