### ISSUE TITLE
How to get cropped image as bitmap after selecting freehandview?

### ISSUE THREAD

**Issue by krtanwar** [davemorrissey/subsampling-scale-image-view#450] opened 2018-11-18 10:35 UTC
*Please provide as much of the following information as possible. Please do not raise issues to ask for help developing your app.*

### Steps to reproduce

(Include your setup code, and where relevant, your layout XML)

### Affected devices

(Specific devices, screen densities, SDK versions)

### Affected images

(Attach images you have problems with)

**Comment by KnIfER** [comment] 2019-07-20 15:55
you can tell your phone to take a screenshot

**Comment by davemorrissey** [comment] 2020-02-26 23:55
Duplicate of #19.

**Closed by davemorrissey** 2020-02-26 23:55 UTC
